apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-cm
  namespace: bankapp
data:
  MYSQL_DATABASE: bankapp_db
  MYSQL_HOST: mysql-service
  MYSQL_PORT: "3306"
  MYSQL_USER: bankapp_dbuser
  OLLAMA_URL: http://ollama:11434
